# Generated by Django 4.2.5 on 2024-08-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название события')),
                ('start_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало события')),
                ('period', models.IntegerField(blank=True, null=True, verbose_name='Период')),
            ],
        ),
    ]
